services:
  postgres:
    image: postgres:15-alpine
    container_name: areeb_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: areeb_db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Add this line to mount the init scripts
      - ./database/schema:/docker-entrypoint-initdb.d
    ports:
      # Try using this IP to connect in pgadmin4 172.26.0.2
      - "5432:5432"
    networks:
      - areeb_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: areeb_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - areeb_network
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: areeb_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - areeb_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  areeb_network:
    driver: bridge
