const ns1 = {
	appTitle: "إيفنتلي",
	navigation: {
		events: "الفعاليات",
		myBookings: "حجوزاتي",
		dashboard: "لوحة التحكم",
		login: "تسجيل الدخول",
		logout: "تسجيل الخروج",
	},
	landingPage: {
		title: "اكتشف واحجز فعاليات مذهلة",
		subtitle:
			"Evently هي منصتك المثالية للعثور على واستكشاف وحجز تذاكر لأروع الفعاليات من حولك. من الحفلات الموسيقية إلى المؤتمرات، لدينا كل ما تحتاجه!",
		browseEventsButton: "تصفح الفعاليات",
		whyChooseTitle: "لماذا تختار Evently؟",
		wideVarietyTitle: "تشكيلة واسعة",
		wideVarietyDescription:
			"استمتع بمجموعة متنوعة من الفعاليات، من اللقاءات المحلية إلى المهرجانات العالمية.",
		easyBookingTitle: "حجز سهل",
		easyBookingDescription:
			"احجز مكانك بنقرات قليلة من خلال عملية الحجز السلسة لدينا.",
		stayUpdatedTitle: "ابق على اطلاع",
		stayUpdatedDescription:
			"لا تفوت أي شيء! احصل على إشعارات بالفعاليات التي ستحبها.",
	},
	auth: {
		loginTitle: "تسجيل الدخول",
		registerTitle: "تسجيل",
		adminLoginTitle: "تسجيل دخول المسؤول",
		emailLabel: "عنوان البريد الإلكتروني",
		passwordLabel: "كلمة المرور",
		loginButton: "تسجيل الدخول",
		loginAsAdminButton: "تسجيل الدخول كمسؤول",
		registerButton: "تسجيل",
		noAccountPrompt: "ليس لديك حساب؟",
		alreadyAccountPrompt: "هل لديك حساب بالفعل؟",
		registerLink: "سجل",
		loginLink: "تسجيل الدخول",
	},
	events: {
		pageTitle: "الفعاليات القادمة",
		pageSubtitle: "اكتشف واحجز تجربتك القادمة",
		bookedStatus: "محجوز",
		noEventsTitle: "لم يتم العثور على فعاليات في الوقت الحالي.",
		noEventsMessage:
			"يرجى التحقق مرة أخرى في وقت لاحق لمعرفة الفعاليات الجديدة والمثيرة!",
		categoryFilterLabel: "التصنيف:", // Added translation
		allCategories: "جميع التصنيفات", // Added translation
	},
	eventDetails: {
		backLink: "← العودة إلى جميع الفعاليات",
		descriptionTitle: "وصف الفعالية",
		noDescription: "لا يوجد وصف مقدم.",
		dateTimeTitle: "التاريخ والوقت",
		venueTitle: "المكان",
		categoryTitle: "التصنيف",
		priceTitle: "السعر",
		bookedStatus: "محجوز",
		alreadyBookedButton: "محجوز بالفعل",
		bookButton: "احجز هذه الفعالية",
		bookingButtonLoading: "جار الحجز...",
		bookingSuccessMessage: "تم الحجز بنجاح!",
		bookingErrorMessage: "حدث خطأ غير متوقع أثناء الحجز.",
		bookingCTA: "احجز مكانك الآن! الأماكن محدودة.",
	},
	bookingSuccess: {
		title: "تم تأكيد الحجز!",
		subtitle: "تهانينا! أنت على استعداد تام ل:",
		datePrefix: "التاريخ:",
		emailConfirmation:
			"سوف تتلقى رسالة تأكيد بالبريد الإلكتروني قريبا مع كل التفاصيل. يمكنك أيضا عرض الحجز الخاص بك في حسابك.",
		viewBookingsButton: "عرض حجوزاتي",
		exploreEventsButton: "استكشاف المزيد من الفعاليات",
		thankYouMessage: "شكرا لاختيارك Evently!",
	},
	myBookings: {
		pageTitle: "حجوزاتي",
		pageSubtitle: "الفعاليات والتجارب التي قمت بحجزها",
		eventDatePrefix: "تاريخ الفعالية:",
		venuePrefix: "المكان:",
		categoryPrefix: "التصنيف:",
		bookedOnPrefix: "تم الحجز في:",
		priceLabel: "السعر",
		viewEventButton: "عرض الفعالية",
		cancelButton: "إلغاء",
		cancellingButton: "جار الإلغاء...",
		cancelConfirmation: "هل أنت متأكد أنك تريد إلغاء هذا الحجز؟",
		cancelSuccess: "تم إلغاء الحجز بنجاح!",
		cancelError: "خطأ في إلغاء الحجز: {{message}}",
		noBookingsTitle: "لم تقم بحجز أية فعاليات حتى الآن.",
		noBookingsMessage: "ابحث عن فعالية تهمك وقم بحجزها!",
		exploreEventsButton: "استكشاف الفعاليات",
	},
	admin: {
		dashboardTitle: "إدارة الفعاليات",
		createNewEventButton: "إنشاء فعالية جديدة",
		tableHeaders: {
			eventName: "اسم الفعالية",
			category: "التصنيف",
			date: "التاريخ",
			venue: "المكان",
			price: "السعر ($)",
			actions: "الإجراءات",
		},
		editButton: "تعديل",
		deleteButton: "حذف",
		deleteConfirmation:
			"هل أنت متأكد أنك تريد حذف هذه الفعالية؟ لا يمكن التراجع عن هذا الإجراء.",
		deleteSuccess: "تم حذف الفعالية بنجاح!",
		deleteError: "خطأ في حذف الفعالية: {{message}}",
		noEventsTitle: "لم يتم العثور على فعاليات.",
		noEventsMessage: "ابدأ بإنشاء أول فعالية لك.",
		createEventButton: "إنشاء فعالية",
		editEventTitle: "تعديل الفعالية:",
		createEventTitle: "إنشاء فعالية جديدة",
		updateEventButton: "تحديث الفعالية",
		submittingButton: "جار الإرسال...",
		cancelButton: "إلغاء",
		submissionError: "حدث خطأ. يرجى المحاولة مرة أخرى.",
		imageLabel: "صورة",
		selectedFilePrefix: "الملف المحدد:",
		failedToLoadError: "تعذر تحميل بيانات الفعالية.",
		failedToUpdateError: "فشل تحديث الفعالية.",
		failedToCreateError: "فشل إنشاء الفعالية.",
	},
	errorPage: {
		title: "عذراً! حدث خطأ ما",
		eventNotFound: "لم يتم العثور على الفعالية بالرقم {{eventId}}.",
		failedToLoadEvent: "فشل تحميل الفعالية {{eventId}}.",
		genericLoadError: "تعذر علينا تحميل {{item}}.",
		backButton: "العودة إلى {{item}}",
		tryAgainButton: "حاول مرة أخرى",
	},
	components: {
		eventForm: {
			eventNameLabel: "اسم الفعالية",
			eventNamePlaceholder: "مثال: مهرجان موسيقى الصيف",
			descriptionLabel: "الوصف",
			descriptionPlaceholder: "صف الفعالية...",
			categoryLabel: "التصنيف",
			categoryPlaceholder: "مثال: موسيقى، تكنولوجيا",
			dateLabel: "التاريخ",
			venueLabel: "المكان",
			venuePlaceholder: "مثال: سنترال بارك",
			priceLabel: "السعر ($)",
			pricePlaceholder: "مثال: 50",
			imageLabel: "صورة",
			selectedFilePrefix: "الملف المحدد:",
			submitButton: "إرسال",
			submittingButton: "جار الإرسال...",
			cancelButton: "إلغاء",
			submissionError: "حدث خطأ. يرجى المحاولة مرة أخرى.",
		},
	},
	date: {
		longFormat: "{{date, datetime}}",
	},
} as const;

export default ns1;
