import type { EventCategory } from "@repo/areeb-backend/consts/event-categories";

const ns1 = {
	appTitle: "Evently",
	navigation: {
		events: "Events",
		myBookings: "My Bookings",
		dashboard: "Dashboard",
		login: "Login",
		logout: "Logout",
	},
	landingPage: {
		title: "Discover & Book Amazing Events",
		subtitle:
			"Evently is your ultimate platform to find, explore, and book tickets for the most exciting events happening around you. From concerts to conferences, we've got you covered!",
		browseEventsButton: "Browse Events",
		whyChooseTitle: "Why Choose Evently?",
		wideVarietyTitle: "Wide Variety",
		wideVarietyDescription:
			"Access a diverse range of events, from local meetups to international festivals.",
		easyBookingTitle: "Easy Booking",
		easyBookingDescription:
			"Secure your spot in just a few clicks with our seamless booking process.",
		stayUpdatedTitle: "Stay Updated",
		stayUpdatedDescription:
			"Never miss out! Get notifications for events you'll love.",
	},
	auth: {
		loginTitle: "Login",
		registerTitle: "Register",
		adminLoginTitle: "Admin Login",
		emailLabel: "Email Address",
		passwordLabel: "Password",
		loginButton: "Login",
		loginAsAdminButton: "Login as Admin",
		registerButton: "Register",
		noAccountPrompt: "Don't have an account?",
		alreadyAccountPrompt: "Already have an account?",
		registerLink: "Register",
		loginLink: "Login",
	},
	events: {
		pageTitle: "Upcoming Events",
		pageSubtitle: "Discover and book your next experience",
		bookedStatus: "Booked",
		noEventsTitle: "No events found at the moment.",
		noEventsMessage: "Please check back later for new and exciting events!",
		categoryFilterLabel: "Category:",
		allCategories: "All Categories",
		hurryUpMessage: "Hurry up! Only {{availableTickets}} tickets left!",
		noTicketsAvailable: "No more tickets available",
		categories: {
			Music: "Music",
			Sports: "Sports",
			Conference: "Conference",
			"Food & Drink": "Food & Drink",
			"Arts & Culture": "Arts & Culture",
			Business: "Business",
			"Health & Wellness": "Health & Wellness",
			"Film & Media": "Film & Media",
			Community: "Community",
			"Tours & Sightseeing": "Tours & Sightseeing",
			Technology: "Technology",
			"Charity & Causes": "Charity & Causes",
			"Workshops & Classes": "Workshops & Classes",
			"Hobbies & Skills": "Hobbies & Skills",
			Literature: "Literature",
			Gaming: "Gaming",
			Seasonal: "Seasonal",
			"Business & Entrepreneurship": "Business & Entrepreneurship",
			"Sports & Fitness": "Sports & Fitness",
			"Holiday & Celebration": "Holiday & Celebration",
		} satisfies Record<EventCategory, string>,
	},
	eventDetails: {
		backLink: "← Back to All Events",
		descriptionTitle: "Event Description",
		noDescription: "No description provided.",
		dateTimeTitle: "Date & Time",
		venueTitle: "Venue",
		categoryTitle: "Category",
		priceTitle: "Price",
		bookedStatus: "Booked",
		alreadyBookedButton: "Already Booked",
		bookButton: "Book This Event",
		bookingButtonLoading: "Booking...",
		bookingSuccessMessage: "Booking successful!",
		bookingErrorMessage: "An unexpected error occurred during booking.",
		bookingCTA: "Secure your spot now! Limited availability.",
	},
	bookingSuccess: {
		title: "Booking Confirmed!",
		subtitle: "Congratulations! You're all set for:",
		datePrefix: "Date:",
		emailConfirmation:
			"You'll receive a confirmation email shortly with all the details. You can also view your booking in your account.",
		viewBookingsButton: "View My Bookings",
		exploreEventsButton: "Explore More Events",
		thankYouMessage: "Thank you for choosing Evently!",
	},
	myBookings: {
		pageTitle: "My Bookings",
		pageSubtitle: "Your booked events and experiences",
		eventDatePrefix: "Event Date",
		venuePrefix: "Venue",
		categoryPrefix: "Category",
		bookedOnPrefix: "Booked on",
		priceLabel: "Price",
		viewEventButton: "View Event",
		cancelButton: "Cancel",
		cancellingButton: "Cancelling...",
		cancelConfirmation: "Are you sure you want to cancel this booking?",
		cancelSuccess: "Booking cancelled successfully!",
		cancelError: "Error cancelling booking: {{message}}",
		noBookingsTitle: "You haven't booked any events yet.",
		noBookingsMessage: "Find an event you're interested in and book it!",
		exploreEventsButton: "Explore Events",
	},
	admin: {
		dashboardTitle: "Events Management",
		createNewEventButton: "Create New Event",
		tableHeaders: {
			eventName: "Event Name",
			category: "Category",
			date: "Date",
			venue: "Venue",
			price: "Price ($)",
			actions: "Actions",
		},
		editButton: "Edit",
		deleteButton: "Delete",
		deleteConfirmation:
			"Are you sure you want to delete this event? This action cannot be undone.",
		deleteSuccess: "Event deleted successfully!",
		deleteError: "Error deleting event: {{message}}",
		noEventsTitle: "No events found.",
		noEventsMessage: "Get started by creating your first event.",
		createEventButton: "Create Event",
		editEventTitle: "Edit Event:",
		createEventTitle: "Create New Event",
		updateEventButton: "Update Event",
		submittingButton: "Submitting...",
		cancelButton: "Cancel",
		submissionError: "An error occurred. Please try again.",
		imageLabel: "Image",
		selectedFilePrefix: "Selected file:",
		failedToLoadError: "Event data could not be loaded.",
		failedToUpdateError: "Failed to update event.",
		failedToCreateError: "Failed to create event.",
	},
	errorPage: {
		title: "Oops! Something Went Wrong",
		eventNotFound: "Event with ID {{eventId}} not found.",
		failedToLoadEvent: "Failed to load event {{eventId}}.",
		genericLoadError: "We couldn't load the {{item}}.",
		backButton: "Back to {{item}}",
		tryAgainButton: "Try Again",
	},
	components: {
		eventForm: {
			eventNameLabel: "Event Name",
			eventNamePlaceholder: "e.g., Summer Music Festival",
			descriptionLabel: "Description",
			descriptionPlaceholder: "Describe the event...",
			categoryLabel: "Category",
			categoryPlaceholder: "e.g., Music, Technology",
			dateLabel: "Date",
			venueLabel: "Venue",
			venuePlaceholder: "e.g., Central Park",
			priceLabel: "Price ($)",
			pricePlaceholder: "e.g., 50",
			imageLabel: "Image",
			selectedFilePrefix: "Selected file:",
			submitButton: "Submit",
			submittingButton: "Submitting...",
			cancelButton: "Cancel",
			submissionError: "An error occurred. Please try again.",
		},
	},
	date: {
		longFormat: "{{date, datetime}}",
	},
	pagination: {
		previous: "Previous",
		next: "Next",
		first: "First",
		last: "Last",
	},
} as const;

export default ns1;
